language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "nightly"
cache: pip
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then travis_retry pip install -U flake8; fi
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then travis_retry flake8; fi
  - python setup.py test
